### ISSUE TITLE
Decrease padding

### ISSUE THREAD

**Issue by denysvitali** [rings-social/frontend#7]
As pointed out on these HN comments:
- https://news.ycombinator.com/item?id=36567231
- https://news.ycombinator.com/item?id=36568295

> One annoyance about the UI (for me at least) is the real lack of information density. Hacker News manages to show 15 stories without even scrolling, while this manages to present... 3?
For starters, individual posts in the Explore view[0] are wayyyy too big, while not providing much information at all. Look at the Comments button, for instance: why is that on a separate line?
>
>After 5 minutes of experimentation, I was able to condense the post item down to the following: https://i.imgur.com/KthkpPQ.png While it does have some kinks, it looks much better and presents a greater amount of information in about 30% less space. Low-hanging fruit, I'd say.
>
> [0]: https://rings.social/r/popular

It would be a good idea to address these comments, I think they're right and I might have exaggerated with the padding (currently set in general to `16px 16px`)

**Comment by tentacleuno** [comment]
It's worse when you consider that, in my image, I actually changed the padding globally for the elements.  Therefore, the ones below the more compact one are still somewhat more compacted than the default.

A more accurate portrayal would be: https://i.imgur.com/z0FGPjp.png

> The comment button is on a separate line because it's part of the post "actions".
> As the site grows we'll add more actions most likely, and those will end up on that line.

It would still be good to have a more compact design :-)

**Comment by denysvitali** [comment]
![image](https://github.com/rings-social/frontend/assets/4939519/f050d8c8-3afb-4612-9ac4-7828806b1d86)

Here is a more compact version that I'll push in a few seconds :)

**Comment by denysvitali** [comment]
Closing as this was fixed in 5529ea0.
Feel free to comment if you think the issue is still there, then I'll reopen this :)
